tap "heroku/brew"
tap "cloudfoundry/tap"
tap "homebrew/dupes"
tap "homebrew/fuse"
tap "homebrew/science"
tap "homebrew/core"
tap "homebrew/versions"
tap "homebrew/binary"
tap "homebrew/x11"
tap "homebrew/bundle"
tap "homebrew/services"
tap "sanemat/font"
tap "go-delve/delve"
tap "caskroom/versions"
tap "caskroom/cask"
tap "rcmdnk/file"
brew "apr"
brew "openssl"
brew "apr-util"
brew "gcc", link: false
brew "arpack"
brew "aspcud"
brew "autoconf"
brew "automake"
brew "aws-elasticbeanstalk"
brew "sqlite"
brew "xz", args: ["universal"]
brew "python"
brew "awscli"
brew "bazel"
brew "freetype"
brew "fontconfig"
brew "gettext"
brew "libffi"
brew "pixman"
brew "camlp4"
brew "ccat"
brew "cf"
brew "cmake"
brew "cocoapods"
brew "coreutils"
brew "cscope"
brew "ctags"
brew "curl"
brew "zeromq"
brew "czmq"
brew "go"
brew "direnv"
brew "elm"
brew "ghostscript"
brew "epstool"
brew "lame"
brew "xvid"
brew "ffmpeg"
brew "flac"
brew "fltk"
brew "icu4c"
brew "harfbuzz"
brew "libtool", args: ["universal"]
brew "fontforge"
brew "gawk"
brew "gd"
brew "ghc"
brew "ghq"
brew "gibo"
brew "gifsicle"
brew "git"
brew "git-extras"
brew "gl2ps"
brew "glpk"
brew "gnu-tar"
brew "gnuplot"
brew "libunistring"
brew "nettle"
brew "gnutls"
brew "jasper"
brew "graphicsmagick"
brew "graphviz"
brew "szip"
brew "hdf5"
brew "heroku"
brew "hub"
brew "hugo"
brew "imagemagick"
brew "isl@0.14"
brew "jemalloc"
brew "oniguruma"
brew "jq"
brew "libelf"
brew "libevent"
brew "libgcrypt"
brew "libusb", args: ["universal"]
brew "libusb-compat"
brew "libgphoto2"
brew "libicns", args: ["universal"]
brew "libogg"
brew "libvorbis"
brew "libsndfile"
brew "libsodium"
brew "libtermkey"
brew "libuv"
brew "libvterm"
brew "libxml2"
brew "libyaml"
brew "makedepend"
brew "mas"
brew "memcached"
brew "metis"
brew "mongodb", restart_service: true
brew "mono"
brew "msgpack"
brew "net-snmp"
brew "nkf"
brew "nmap"
brew "ntfs-3g"
brew "opam"
brew "peco"
brew "plotutils"
brew "portaudio"
brew "postgresql"
brew "pyenv"
brew "qt"
brew "qhull"
brew "qscintilla2"
brew "ruby-build"
brew "rbenv"
brew "redis"
brew "rename"
brew "sane-backends"
brew "sl"
brew "tbb"
brew "tig"
brew "travis"
brew "tree"
brew "unibilium"
brew "unixodbc"
brew "vim"
brew "watchman"
brew "wget"
brew "wine"
brew "wxmac"
brew "yarn"
brew "youtube-dl"
brew "zlib"
brew "zsh"
brew "cloudfoundry/tap/cf-cli", link: false
brew "rcmdnk/file/brew-file"
brew "sanemat/font/ricty", args: ["vim-powerline"]
cask "alfred"
cask "android-studio"
cask "atom"
cask "bettertouchtool"
cask "db-browser-for-sqlite"
cask "dropbox"
cask "flux"
cask "gitify"
cask "graphiql"
cask "gyazo"
cask "hyper"
cask "insomnia"
cask "intel-haxm"
cask "iterm2"
cask "karabiner"
cask "kindle"
cask "licecap"
cask "ngrok"
cask "pycharm-edu"
cask "sketch-toolbox"
cask "skim"
cask "skitch"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"
mas "1Password", id: 443987910
mas "Affinity Designer", id: 824171161
mas "Display Menu", id: 549083868
mas "Gifski", id: 1351639930
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PixelScheduler", id: 976996075
mas "Slack", id: 803453959
mas "StuffIt Expander", id: 405580712
mas "Tomato One", id: 907364780
mas "Xcode", id: 497799835
